# Generated by Django 4.0.3 on 2023-10-19 23:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='Ex: University of Nigeria', max_length=100)),
                ('degree', models.CharField(help_text='Ex: Bachelors', max_length=100)),
                ('field_of_study', models.CharField(help_text='Ex: Computer Science', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(help_text='Describe your studies, awards, e.t.c')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Ex: Software Engineer', max_length=100)),
                ('company', models.CharField(help_text='Ex: Microsoft', max_length=100)),
                ('location', models.CharField(help_text='The address of the company', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('country', django_countries.fields.CountryField(default='NG', max_length=2)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('address', models.CharField(max_length=250)),
                ('zip_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Invalid postal code')])),
                ('date_of_birth', models.DateField(null=True)),
                ('professional_role', models.CharField(help_text='Add a title to tell the world what you do.', max_length=250)),
                ('bio', models.TextField()),
                ('educations', models.ManyToManyField(help_text='You don’t have to have a degree. Adding any relevant education helps make your profile more visible.', related_name='educations', to='application.education')),
                ('languages', models.ManyToManyField(help_text='clients are often interested to know what languages you speak. English is a must, but do you speak any other languages?', to='application.language')),
                ('services', models.ManyToManyField(help_text='Choose at least one service that best describes the type of work you do. This helps us match you with clients who need your unique expertise.', to='application.service')),
                ('skills', models.ManyToManyField(help_text='Your skills show clients what you can offer, and help us choose which jobs to recommend to you.', to='application.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_experiences', models.ManyToManyField(related_name='work_experiences', to='application.workexperience')),
            ],
        ),
    ]
